name: C

on:
  push:
    branches:
      - "trunk"
  pull_request:
  workflow_dispatch:

jobs:
  alpine:
    runs-on: ubuntu-latest
    container: alpine:latest

    steps:
      - name: Install Dependencies
        run: apk add gcc libc-dev

      - name: Checkout
        uses: actions/checkout@v4

      - name: Bootstrap nob
        run: cc -Werror -o nob nob.c

      - name: Build
        run: ./nob

      - name: Run Program
        run: ./generate-names


  debian:
    runs-on: ubuntu-latest
    container: debian:latest

    steps:
      - name: Install Dependencies
        run: |
          apt update
          apt install -y gcc

      - name: Checkout
        uses: actions/checkout@v4

      - name: Bootstrap nob
        run: cc -Werror -o nob nob.c

      - name: Build
        run: ./nob

      - name: Run Program
        run: ./generate-names


  void-glibc:
    runs-on: ubuntu-latest
    container: ghcr.io/void-linux/void-glibc:latest
    steps:
      - name: Install dependencies
        run: xbps-install -Sy git gcc

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Bootstrap nob
        run: cc -Werror -o nob nob.c

      - name: Build
        run: ./nob

      - name: Run Program
        run: ./generate-names


  macos:
    runs-on: macos-latest
    steps:
      # Note: gcc is already installed on macos runner
      # - name: Install Dependencies
      #   run: brew install gcc

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Bootstrap nob
        run: cc -Werror -o nob nob.c

      - name: Build
        run: ./nob

      - name: Run Program
        run: ./generate-names
